version: '3.4'

services:
  db:
    image: postgres:9.4
    container_name: postgres_database
    restart: always
    env_file:
      - .env
    volumes:
    - /todo_list_app/postgres:/var/lib/postgresql/data

  backend_migrations:
    image: itdevelatt/todo-list-backend:${TAG}
    container_name: backend_migrations
    build:
      dockerfile: ./Dockerfile
      context: ./todo-list-backend-api
    command: 'bundle exec rake db:migrate'
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db

  backend:
    image: itdevelatt/todo-list-backend:${TAG}
    container_name: backend
    build:
      dockerfile: ./Dockerfile
      context: ./todo-list-backend-api
    command: 'bundle exec rails s -b 0.0.0.0 -p 3000'
    restart: always
    env_file:
      - .env
    depends_on:
      - backend_migrations
      - db

  frontend:
    image: itdevelatt/todo-list-frontend:${TAG}
    container_name: frontend
    depends_on:
      - backend
    build:
      dockerfile: ./Dockerfile
      context: ./todo-list-ui
      args:
        BUILD_ENV: production
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.frontend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx.proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
